/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as ApiPublicServiceImageRouteImport } from './routes/api/public/service-image'
import { Route as ApiPublicReverseGeocodeRouteImport } from './routes/api/public/reverse-geocode'
import { Route as ApiPublicHasLoginPinRouteImport } from './routes/api/public/has-login-pin'
import { Route as ApiPublicGeocodeSearchRouteImport } from './routes/api/public/geocode-search'
import { Route as ApiPublicWebhooksRazorpayRouteImport } from './routes/api/public/webhooks/razorpay'
import { Route as ApiPublicCourierProcessRefundsRouteImport } from './routes/api/public/courier/process-refunds'
import { Route as ApiPublicAdminAlertProcessRouteImport } from './routes/api/public/admin-alert/process'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicServiceImageRoute = ApiPublicServiceImageRouteImport.update({
  id: '/api/public/service-image',
  path: '/api/public/service-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReverseGeocodeRoute = ApiPublicReverseGeocodeRouteImport.update({
  id: '/api/public/reverse-geocode',
  path: '/api/public/reverse-geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHasLoginPinRoute = ApiPublicHasLoginPinRouteImport.update({
  id: '/api/public/has-login-pin',
  path: '/api/public/has-login-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGeocodeSearchRoute = ApiPublicGeocodeSearchRouteImport.update({
  id: '/api/public/geocode-search',
  path: '/api/public/geocode-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksRazorpayRoute =
  ApiPublicWebhooksRazorpayRouteImport.update({
    id: '/api/public/webhooks/razorpay',
    path: '/api/public/webhooks/razorpay',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCourierProcessRefundsRoute =
  ApiPublicCourierProcessRefundsRouteImport.update({
    id: '/api/public/courier/process-refunds',
    path: '/api/public/courier/process-refunds',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminAlertProcessRoute =
  ApiPublicAdminAlertProcessRouteImport.update({
    id: '/api/public/admin-alert/process',
    path: '/api/public/admin-alert/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invite/$code': typeof InviteCodeRoute
  '/api/public/geocode-search': typeof ApiPublicGeocodeSearchRoute
  '/api/public/has-login-pin': typeof ApiPublicHasLoginPinRoute
  '/api/public/reverse-geocode': typeof ApiPublicReverseGeocodeRoute
  '/api/public/service-image': typeof ApiPublicServiceImageRoute
  '/api/public/admin-alert/process': typeof ApiPublicAdminAlertProcessRoute
  '/api/public/courier/process-refunds': typeof ApiPublicCourierProcessRefundsRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite/$code': typeof InviteCodeRoute
  '/api/public/geocode-search': typeof ApiPublicGeocodeSearchRoute
  '/api/public/has-login-pin': typeof ApiPublicHasLoginPinRoute
  '/api/public/reverse-geocode': typeof ApiPublicReverseGeocodeRoute
  '/api/public/service-image': typeof ApiPublicServiceImageRoute
  '/api/public/admin-alert/process': typeof ApiPublicAdminAlertProcessRoute
  '/api/public/courier/process-refunds': typeof ApiPublicCourierProcessRefundsRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invite/$code': typeof InviteCodeRoute
  '/api/public/geocode-search': typeof ApiPublicGeocodeSearchRoute
  '/api/public/has-login-pin': typeof ApiPublicHasLoginPinRoute
  '/api/public/reverse-geocode': typeof ApiPublicReverseGeocodeRoute
  '/api/public/service-image': typeof ApiPublicServiceImageRoute
  '/api/public/admin-alert/process': typeof ApiPublicAdminAlertProcessRoute
  '/api/public/courier/process-refunds': typeof ApiPublicCourierProcessRefundsRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invite/$code'
    | '/api/public/geocode-search'
    | '/api/public/has-login-pin'
    | '/api/public/reverse-geocode'
    | '/api/public/service-image'
    | '/api/public/admin-alert/process'
    | '/api/public/courier/process-refunds'
    | '/api/public/webhooks/razorpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invite/$code'
    | '/api/public/geocode-search'
    | '/api/public/has-login-pin'
    | '/api/public/reverse-geocode'
    | '/api/public/service-image'
    | '/api/public/admin-alert/process'
    | '/api/public/courier/process-refunds'
    | '/api/public/webhooks/razorpay'
  id:
    | '__root__'
    | '/'
    | '/invite/$code'
    | '/api/public/geocode-search'
    | '/api/public/has-login-pin'
    | '/api/public/reverse-geocode'
    | '/api/public/service-image'
    | '/api/public/admin-alert/process'
    | '/api/public/courier/process-refunds'
    | '/api/public/webhooks/razorpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InviteCodeRoute: typeof InviteCodeRoute
  ApiPublicGeocodeSearchRoute: typeof ApiPublicGeocodeSearchRoute
  ApiPublicHasLoginPinRoute: typeof ApiPublicHasLoginPinRoute
  ApiPublicReverseGeocodeRoute: typeof ApiPublicReverseGeocodeRoute
  ApiPublicServiceImageRoute: typeof ApiPublicServiceImageRoute
  ApiPublicAdminAlertProcessRoute: typeof ApiPublicAdminAlertProcessRoute
  ApiPublicCourierProcessRefundsRoute: typeof ApiPublicCourierProcessRefundsRoute
  ApiPublicWebhooksRazorpayRoute: typeof ApiPublicWebhooksRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/service-image': {
      id: '/api/public/service-image'
      path: '/api/public/service-image'
      fullPath: '/api/public/service-image'
      preLoaderRoute: typeof ApiPublicServiceImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reverse-geocode': {
      id: '/api/public/reverse-geocode'
      path: '/api/public/reverse-geocode'
      fullPath: '/api/public/reverse-geocode'
      preLoaderRoute: typeof ApiPublicReverseGeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/has-login-pin': {
      id: '/api/public/has-login-pin'
      path: '/api/public/has-login-pin'
      fullPath: '/api/public/has-login-pin'
      preLoaderRoute: typeof ApiPublicHasLoginPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/geocode-search': {
      id: '/api/public/geocode-search'
      path: '/api/public/geocode-search'
      fullPath: '/api/public/geocode-search'
      preLoaderRoute: typeof ApiPublicGeocodeSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/razorpay': {
      id: '/api/public/webhooks/razorpay'
      path: '/api/public/webhooks/razorpay'
      fullPath: '/api/public/webhooks/razorpay'
      preLoaderRoute: typeof ApiPublicWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/courier/process-refunds': {
      id: '/api/public/courier/process-refunds'
      path: '/api/public/courier/process-refunds'
      fullPath: '/api/public/courier/process-refunds'
      preLoaderRoute: typeof ApiPublicCourierProcessRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-alert/process': {
      id: '/api/public/admin-alert/process'
      path: '/api/public/admin-alert/process'
      fullPath: '/api/public/admin-alert/process'
      preLoaderRoute: typeof ApiPublicAdminAlertProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InviteCodeRoute: InviteCodeRoute,
  ApiPublicGeocodeSearchRoute: ApiPublicGeocodeSearchRoute,
  ApiPublicHasLoginPinRoute: ApiPublicHasLoginPinRoute,
  ApiPublicReverseGeocodeRoute: ApiPublicReverseGeocodeRoute,
  ApiPublicServiceImageRoute: ApiPublicServiceImageRoute,
  ApiPublicAdminAlertProcessRoute: ApiPublicAdminAlertProcessRoute,
  ApiPublicCourierProcessRefundsRoute: ApiPublicCourierProcessRefundsRoute,
  ApiPublicWebhooksRazorpayRoute: ApiPublicWebhooksRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
